import { StyleSheet, Platform } from 'react-native';

/**
 * Home map + bottom sheet styles driven by semantic theme colors.
 * Map props (tiles, polylines) stay unchanged; sheet chrome follows light/dark.
 */
export function createHomeStyles(c) {
  return StyleSheet.create({
    locationBannerWrap: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 48 : 10,
      left: 0,
      right: 0,
      zIndex: 70,
      elevation: 70,
      alignItems: 'center',
      paddingHorizontal: 12,
    },
    locationBanner: {
      width: '100%',
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderWidth: 1,
      shadowColor: '#000',
      shadowOpacity: 0.18,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
    },
    locationBannerTitle: { fontSize: 14, fontWeight: '900' },
    locationBannerSubtitle: { marginTop: 2, fontSize: 12, fontWeight: '700' },
    container: { flex: 1, backgroundColor: '#000' },
    mapFull: { ...StyleSheet.absoluteFillObject },
    map: { flex: 1 },
    loadingMap: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: c.surface },
    loadingText: { marginTop: 8, color: c.textSecondary },
    mapLoaderOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.mapLoaderBg,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 5,
    },
    mapLoaderText: { marginTop: 10, color: c.textSecondary, fontWeight: '600' },
    locationModalOverlay: {
      flex: 1,
      backgroundColor: c.overlay,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 18,
    },
    locationModalCard: {
      width: '100%',
      maxWidth: 420,
      backgroundColor: c.surfaceElevated,
      borderRadius: 20,
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 18,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: c.border,
    },
    locationPulseWrap: { width: 136, height: 136, alignItems: 'center', justifyContent: 'center' },
    locationPulse3: { position: 'absolute', width: 122, height: 122, borderRadius: 61, backgroundColor: c.accentSoft },
    locationPulse2: { position: 'absolute', width: 96, height: 96, borderRadius: 48, backgroundColor: c.accentSoft },
    locationPulse1: { position: 'absolute', width: 72, height: 72, borderRadius: 36, backgroundColor: c.accentSoft },
    locationPulseCenter: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: c.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    locationModalTitle: { marginTop: 8, fontSize: 32, fontWeight: '700', color: c.text },
    locationModalSubtitle: {
      marginTop: 12,
      fontSize: 16,
      lineHeight: 24,
      color: c.textMuted,
      textAlign: 'center',
      paddingHorizontal: 6,
    },
    locationPrimaryBtn: {
      marginTop: 22,
      width: '100%',
      backgroundColor: c.accent,
      borderRadius: 10,
      paddingVertical: 14,
      alignItems: 'center',
    },
    locationPrimaryBtnText: { color: c.onAccent, fontSize: 17, fontWeight: '700' },
    locationSettingsBtn: { marginTop: 12, paddingVertical: 8, paddingHorizontal: 12 },
    locationSettingsBtnText: { color: c.accentSecondary, fontSize: 16, fontWeight: '700' },
    locationSkipBtn: { marginTop: 2, paddingVertical: 10, paddingHorizontal: 12 },
    locationSkipBtnText: { color: c.textMuted, fontSize: 18, fontWeight: '600' },
    sheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: '88%',
      backgroundColor: c.sheet,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      padding: 16,
      zIndex: 2,
      elevation: 2,
      borderTopWidth: 1,
      borderColor: c.border,
    },
    sheetHandleArea: { alignItems: 'center', paddingTop: 2, paddingBottom: 10 },
    sheetHandle: { width: 42, height: 4, borderRadius: 999, backgroundColor: c.sheetHandle },
    modeRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
    modeBtn: {
      flex: 1,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      paddingVertical: 8,
      alignItems: 'center',
    },
    modeBtnActive: { backgroundColor: c.accent, borderColor: c.accent },
    modeBtnText: { color: c.textSecondary, fontWeight: '600' },
    modeBtnTextActive: { color: c.onAccent },
    tipText: { color: c.textMuted, marginBottom: 10, fontSize: 12 },
    locateBtn: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      paddingVertical: 10,
      alignItems: 'center',
      marginBottom: 8,
    },
    locateBtnText: { color: c.accent, fontWeight: '700' },
    locationError: { marginTop: 8, marginHorizontal: 16, color: c.danger, fontSize: 12 },
    debugText: { marginTop: 6, marginBottom: 8, marginHorizontal: 0, color: c.textMuted, fontSize: 12 },
    resultsHeader: {
      backgroundColor: c.surface,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    resultsHeaderText: { flex: 1, paddingRight: 12 },
    resultsTitle: { fontSize: 18, fontWeight: '700', color: c.text },
    resultsSubtitle: { marginTop: 4, color: c.textSecondary, fontSize: 12 },
    bookingStatus: { marginTop: 6, color: c.success, fontSize: 12, fontWeight: '600' },
    changeLocationsBtn: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.chipInactive,
    },
    changeLocationsText: { fontWeight: '700', color: c.textSecondary },
    resultsListContent: { paddingBottom: 24 },
    rideTypeRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
    rideTypeRaster: { width: 26, height: 26 },
    rideTypeRasterActive: { tintColor: c.onAccent },
    rideTypeChip: {
      flex: 1,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 999,
      paddingVertical: 10,
      alignItems: 'center',
      backgroundColor: c.chipInactive,
    },
    rideTypeChipActive: { backgroundColor: c.chipActive, borderColor: c.chipActive },
    carAcRow: { flexDirection: 'row', gap: 8, marginTop: 8 },
    carAcChip: {
      flex: 1,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      paddingVertical: 8,
      alignItems: 'center',
      backgroundColor: c.surfaceElevated,
    },
    carAcChipActive: { backgroundColor: c.accentSoft, borderColor: c.accent },
    carAcChipText: { fontSize: 12, fontWeight: '700', color: c.textMuted },
    carAcChipTextActive: { color: c.accentSecondary },
    inputRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    inputFlex: { flex: 1, marginBottom: 0, paddingRight: 44 },
    clearBtn: {
      position: 'absolute',
      right: 10,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: c.chipInactive,
      alignItems: 'center',
      justifyContent: 'center',
    },
    clearBtnText: { fontSize: 18, color: c.textSecondary, fontWeight: '700', marginTop: -2 },
    input: { borderWidth: 1, borderColor: c.border, padding: 12, borderRadius: 10, marginBottom: 10, color: c.text, backgroundColor: c.surfaceElevated },
    button: { backgroundColor: c.accent, padding: 15, borderRadius: 8, alignItems: 'center' },
    buttonText: { color: c.onAccent, fontWeight: 'bold' },
    sortBtn: { marginTop: 10, alignSelf: 'flex-end' },
    sortBtnText: { color: c.accentSecondary, fontSize: 12 },
    disclaimer: { fontSize: 10, color: c.textMuted, marginTop: 10, fontStyle: 'italic' },
    compareBtn: {
      marginTop: 0,
      backgroundColor: c.accent,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: 'center',
    },
    compareBtnText: { color: c.onAccent, fontWeight: '800' },
    captureLiveBtn: {
      marginTop: 10,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 12,
      paddingVertical: 11,
      alignItems: 'center',
      backgroundColor: c.surfaceElevated,
    },
    captureLiveBtnText: { color: c.accent, fontWeight: '800', fontSize: 13 },
    captureLiveHint: {
      marginTop: 6,
      fontSize: 10,
      color: c.textMuted,
      textAlign: 'center',
      lineHeight: 14,
      paddingHorizontal: 4,
    },
    trafficSurgeChip: {
      marginBottom: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 10,
      borderWidth: 1,
    },
    trafficSurgeChipText: { fontSize: 12, fontWeight: '800' },
    baseFareBanner: {
      marginTop: 0,
      marginBottom: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: c.chipInactive,
      borderWidth: 1,
      borderColor: c.border,
    },
    baseFareLabel: { fontSize: 11, fontWeight: '800', color: c.textMuted, textTransform: 'uppercase', letterSpacing: 0.3 },
    baseFareValue: { marginTop: 4, fontSize: 18, fontWeight: '900', color: c.text },
    baseFareHint: { marginTop: 4, fontSize: 11, color: c.textMuted, fontWeight: '600' },
    fareCard: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      marginHorizontal: 15,
      marginTop: 15,
      backgroundColor: c.surfaceElevated,
      borderRadius: 12,
      elevation: 2,
      borderWidth: 1,
      borderColor: c.border,
    },
    providerName: { fontSize: 18, fontWeight: 'bold', color: c.text },
    rideType: { color: c.textMuted },
    riderText: { color: c.textSecondary, fontSize: 12, marginTop: 4 },
    riderMetaText: { color: c.textSecondary, fontSize: 12, marginTop: 2 },
    priceContainer: { alignItems: 'flex-end' },
    price: { fontSize: 18, fontWeight: 'bold', color: c.success, marginBottom: 5 },
    bookBtn: { backgroundColor: c.accentSecondary, paddingHorizontal: 15, paddingVertical: 5, borderRadius: 8 },
    bookBtnText: { color: c.onAccent, fontSize: 12 },
    emptyText: { textAlign: 'center', marginTop: 40, color: c.textMuted },

    topBar: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 72 : 34,
      left: 12,
      right: 12,
      flexDirection: 'row',
      justifyContent: 'space-between',
      zIndex: 60,
      elevation: 60,
    },
    topBarBtn: {
      backgroundColor: c.surfaceElevated,
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: c.border,
    },
    topBarMenuBtn: {
      width: 46,
      height: 46,
      borderRadius: 12,
      backgroundColor: c.accent,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: c.cardShadow,
      shadowOpacity: 0.2,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
    },
    topBarBellBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: c.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: c.border,
    },

    whereCard: {
      marginBottom: 8,
      borderRadius: 18,
      backgroundColor: c.surfaceElevated,
      borderWidth: 1,
      borderColor: c.border,
      padding: 12,
    },
    whereSearchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 2,
    },
    whereSearchText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '800',
      color: c.textMuted,
    },
    whereSearchTextActive: { color: c.text },

    rideOverlayCover: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      zIndex: 20,
      backgroundColor: c.mapLoaderBg,
      padding: 16,
    },
    rideOverlayCard: {
      flex: 1,
      borderRadius: 18,
      backgroundColor: c.surfaceElevated,
      borderWidth: 1,
      borderColor: c.border,
      paddingBottom: 10,
    },
    rideOverlayHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 14,
      paddingTop: 14,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    rideOverlayTitle: { fontSize: 16, fontWeight: '900', color: c.text },
    rideOverlayChangeBtn: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.chipInactive,
    },
    rideOverlayChangeBtnText: { fontWeight: '900', color: c.textSecondary },
    rideOverlayListContent: { padding: 14, gap: 12, paddingBottom: 24 },

    rideTypeLine: { marginTop: 4, color: c.textSecondary, fontWeight: '700', fontSize: 12 },
    bookBtnDisabled: { opacity: 0.7 },
  });
}
